print('hola mundo')
print('hola mundo')
print('hola mundo')
print('hola mundo')
print('hola mundo')
print('hola mundo')
print('hola mundo')
print('hola mundo')
print('hola mundo')
print('hola mundo')
print("HOla mundo tec ")
print('hola mundo')
print('hola mundo')
print('hola mundo')
print("HOla mundo tec ")
print('hola mundo')
print('hola mundo')
print('hola mundo')
print('hola mundo')
print('hola mundo')
print('hola mundo')
print('hola mundo')
print('hola mundo')
print('hola mundo')
print('hola mundo')
print("HOla mundo tec ")
print('hola mundo')
print('hola mundo')
print('hola mundo')
print("HOla mundo tec ")