print('hola mundo')
print('hola mundo')
print('hola mundo')
print('hola mundo')
print('hola mundo')
print('hola mundo')
print('hola mundo')
print('hola mundo')
print('hola mundo')
print('hola mundo')
print("HOla mundo tec ")